### ISSUE TITLE
no aT.changeDrawFlag()

### ISSUE THREAD

**Issue by antimodular** [KavinHan/ofxAffinetransformation#1]
the addon look promising.

i am trying to comply this on OS X 10.10.2 and OF 0.9.0 and get this error:

/Applications/of_v0.9.0_osx_release/addons/ofxAffinetransformation/example/src/ofApp.cpp:28:6: No member named 'changeDrawFlag' in 'ofxAffineTransformation'

it seems like a function is called that does not exist in the addon. ?
thanks.

**Comment by KavinHan** [comment]
@antimodular thank you and sorry about my mistake~~~^^

already fixed the example problem.

Please check. :)
